
###
GET http://localhost:5001/
###
GET http://localhost:5001/users

###
GET http://localhost:5001/users/3
###
POST http://localhost:5001/users   
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com"
}

###
PUT http://localhost:5001/users/2
Content-Type: application/json

{
    "username": "updateduser",
    "email": "updateduser@example.com"
}
###
DELETE http://localhost:5001/users/4





@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJuZXd1c2VyIiwibmJmIjoxNzY3NzY1NjE5LCJleHAiOjE3Njc3NjkyMTksImlhdCI6MTc2Nzc2NTYxOSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxLyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMS8ifQ.NiTx7PXx1T0MJ6ooN7i0f35LawXOhNbm8YZIYaDUPE0

###
GET http://localhost:5001/dbusers
Authorization: Bearer {{token}}
###
GET http://localhost:5001/dbusers/5
Authorization: Bearer {{token}}

###
POST http://localhost:5001/signup
Content-Type: application/json

{
    "Username": "newuser",
    "PasswordHash": "SecurePassword123",
    "Email": "newuser@example.com"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "Username": "newuser",
    "Password": "SecurePassword123"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "Username": "nedvfgeewuser",
    "Password": "SecurePassword123"
}

###
GET http://localhost:5001/profile
Authorization: Bearer {{token}}
###
GET http://localhost:5001/tasks/
Authorization: Bearer {{token}}

###
GET http://localhost:5001/tasks/3
Authorization: Bearer {{token}}

###
POST http://localhost:5001/tasks/post
Authorization: Bearer {{token}}
Content-Type: application/json  

{
    "title": "New Task",
    "description": "This is a new task",
    "status": 0,
    "dueDate": "2024-12-31T23:59:59Z"
}


###
PUT http://localhost:5001/tasks/update/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Updated Task",
    "description": "This task has been updated",
    "status": 1,
    "dueDate": "2024-12-31T23:59:59Z"
}

###
DELETE http://localhost:5001/tasks/delete/4
Authorization: Bearer {{token}}

