
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJuZXd1c2VyMiIsIm5iZiI6MTc2Nzc2NjA0NiwiZXhwIjoxNzY3NzY5NjQ2LCJpYXQiOjE3Njc3NjYwNDYsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMS8iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvIn0.smN6KnqKq4jy1xBASBd4rqVqcgMXoW_eQfyEpPnu8GA

###
GET http://localhost:5001/dbusers
Authorization: Bearer {{token}}
###
GET http://localhost:5001/dbusers/5
Authorization: Bearer {{token}}

###
POST http://localhost:5001/signup
Content-Type: application/json

{
    "Username": "newuser2",
    "PasswordHash": "SecurePassword123456",
    "Email": "newuser123@example.com"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "Username": "newuser2",
    "Password": "SecurePassword123456"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "Username": "nedvfgeewuser",
    "Password": "SecurePassword123"
}

###
GET http://localhost:5001/profile
Authorization: Bearer {{token}}
###
GET http://localhost:5001/tasks/
Authorization: Bearer {{token}}

###
GET http://localhost:5001/tasks/3
Authorization: Bearer {{token}}

###
POST http://localhost:5001/tasks/post
Authorization: Bearer {{token}}
Content-Type: application/json  

{
    "title": "New Task user 5",
    "description": "This is a new task",
    "status": 0,
    "dueDate": "2026-01-08T23:59:59Z"
}


###
PUT http://localhost:5001/tasks/update/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Updated Task user2",
    "description": "This task has been updated",
    "status": 1,
    "dueDate": "2024-12-31T23:59:59Z"
}

###
DELETE http://localhost:5001/tasks/delete/1
Authorization: Bearer {{token}}

